version: "3.8"
services:
  postgres:
    image: postgres:latest
    networks:
      - local_network
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_in_psg
    volumes:
      - ./postgres/ddl/createuser.sql:/docker-entrypoint-initdb.d/createuser.sql
      - ./postgres/ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/dml/load_data_scripts.sql:/docker-entrypoint-initdb.d/load_data_scripts.sql      
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    networks:
        - local_network
    ulimits:
        nofile:
          soft: 262144
          hard: 262144 
    ports:
      - "8123:8123"
    volumes:
      - "clickhouse-data:/var/lib/clickhouse"
  click-ui:
    image: spoonest/clickhouse-tabix-web-client
    networks:
        - local_network
    depends_on:
      - clickhouse
    ports:
      - "8124:80"
    restart: always
volumes:
  clickhouse-data:
networks:
    local_network:
      driver: bridge
      name: local_network